[package]
name = "u2f"
version = "0.1.0"
authors = ["Chris Dawes <cmsd2@cantab.net>"]

[dependencies]
serde = "0.9"
serde_derive = "0.9"

# serde_json is just for the example, not required in general
serde_json = "0.9"